/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Asks
type Depth struct {
	// quantity
	Quantity int32 `json:"quantity,omitempty"`
	// price
	Price float64 `json:"price,omitempty"`
	// orders
	Orders int32 `json:"orders,omitempty"`
}
