/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Error details for multi order request
type MultiOrderError struct {
	// Unique code for the error state
	ErrorCode string `json:"errorCode,omitempty"`
	// Verbose message for the error state
	Message string `json:"message,omitempty"`
	// Path to property failing validation
	PropertyPath string `json:"propertyPath,omitempty"`
	// Invalid value for the property failing validation
	InvalidValue *interface{} `json:"invalidValue,omitempty"`
	// A unique identifier for tracking individual orders within the batch
	CorrelationId string `json:"correlation_id,omitempty"`
}
