/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for holdings
type HoldingsData struct {
	// The standard ISIN representing stocks listed on multiple exchanges
	Isin string `json:"isin,omitempty"`
	// Quantity either blocked towards open or completed order
	CncUsedQuantity int32 `json:"cnc_used_quantity,omitempty"`
	// Category of collateral assigned by RMS
	CollateralType string `json:"collateral_type,omitempty"`
	// Name of the company
	CompanyName string `json:"company_name,omitempty"`
	// This is the haircut percentage applied from RMS (applicable incase of collateral)
	Haircut float32 `json:"haircut,omitempty"`
	// Shows if the order was either Intraday, Delivery, CO or OCO
	Product string `json:"product,omitempty"`
	// The total holding qty
	Quantity int32 `json:"quantity,omitempty"`
	// Shows the trading symbol of the instrument
	Tradingsymbol string `json:"tradingsymbol,omitempty"`
	// The last traded price of the instrument
	LastPrice float32 `json:"last_price,omitempty"`
	// Closing price of the instrument from the last trading day
	ClosePrice float32 `json:"close_price,omitempty"`
	// Profit and Loss
	Pnl float32 `json:"pnl,omitempty"`
	// Day's change in absolute value for the stock
	DayChange float32 `json:"day_change,omitempty"`
	// Day's change in percentage for the stock
	DayChangePercentage float32 `json:"day_change_percentage,omitempty"`
	// Key issued by Upstox for the instrument
	InstrumentToken string `json:"instrument_token,omitempty"`
	// Average price at which the net holding quantity was acquired
	AveragePrice float32 `json:"average_price,omitempty"`
	// Quantity marked as collateral by RMS on users request
	CollateralQuantity       int32 `json:"collateral_quantity,omitempty"`
	CollateralUpdateQuantity int32 `json:"collateral_update_quantity,omitempty"`
	// Shows the trading symbol of the instrument
	TradingSymbol string `json:"trading_symbol,omitempty"`
	// Quantity on T+1 day after order execution
	T1Quantity int32 `json:"t1_quantity,omitempty"`
	// Exchange of the trading symbol
	Exchange string `json:"exchange,omitempty"`
}
