/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for instrument margin details
type Margin struct {
	// Upfront margin mandatory by exchange for derivatives trade applicable on only FNO trade
	SpanMargin float64 `json:"span_margin,omitempty"`
	// Based on ELM percentage values provided by exchange, applicable on only FNO trade
	ExposureMargin float64 `json:"exposure_margin,omitempty"`
	// Margin applicable for any equity trade
	EquityMargin float64 `json:"equity_margin,omitempty"`
	// Option premium required.
	NetBuyPremium float64 `json:"net_buy_premium,omitempty"`
	// Application margin applicable on MCX FNO trade for certain commodities
	AdditionalMargin float64 `json:"additional_margin,omitempty"`
	// Total margin required for the basket
	TotalMargin float64 `json:"total_margin,omitempty"`
	// Tender margin
	TenderMargin float64 `json:"tender_margin,omitempty"`
}
