/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

import (
	"time"
)

// Response data for option contracts
type InstrumentData struct {
	Name               string    `json:"name,omitempty"`
	Segment            string    `json:"segment,omitempty"`
	Exchange           string    `json:"exchange,omitempty"`
	Isin               string    `json:"isin,omitempty"`
	Expiry             time.Time `json:"expiry,omitempty"`
	Country            string    `json:"country,omitempty"`
	Latency            string    `json:"latency,omitempty"`
	Description        string    `json:"description,omitempty"`
	Currency           string    `json:"currency,omitempty"`
	Weekly             bool      `json:"weekly,omitempty"`
	InstrumentKey      string    `json:"instrument_key,omitempty"`
	ExchangeToken      string    `json:"exchange_token,omitempty"`
	TradingSymbol      string    `json:"trading_symbol,omitempty"`
	ShortName          string    `json:"short_name,omitempty"`
	TickSize           float64   `json:"tick_size,omitempty"`
	LotSize            int64     `json:"lot_size,omitempty"`
	InstrumentType     string    `json:"instrument_type,omitempty"`
	FreezeQuantity     float64   `json:"freeze_quantity,omitempty"`
	UnderlyingKey      string    `json:"underlying_key,omitempty"`
	UnderlyingType     string    `json:"underlying_type,omitempty"`
	UnderlyingSymbol   string    `json:"underlying_symbol,omitempty"`
	LastTradingDate    time.Time `json:"last_trading_date,omitempty"`
	StrikePrice        float64   `json:"strike_price,omitempty"`
	PriceQuoteUnit     string    `json:"price_quote_unit,omitempty"`
	QtyMultiplier      int64     `json:"qty_multiplier,omitempty"`
	MinimumLot         int64     `json:"minimum_lot,omitempty"`
	StartTime          string    `json:"start_time,omitempty"`
	EndTime            string    `json:"end_time,omitempty"`
	WeekDays           string    `json:"week_days,omitempty"`
	GeneralDenominator float64   `json:"general_denominator,omitempty"`
	GeneralNumerator   float64   `json:"general_numerator,omitempty"`
	PriceNumerator     float64   `json:"price_numerator,omitempty"`
	PriceDenominator   float64   `json:"price_denominator,omitempty"`
	MtfEnabled         bool      `json:"mtf_enabled,omitempty"`
	MtfBracket         float64   `json:"mtf_bracket,omitempty"`
	SecurityType       string    `json:"security_type,omitempty"`
}
