/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for charges details
type ProfitAndLossChargesData struct {
	//   Total charges for the user
	Total float32 `json:"total,omitempty"`
	// Brokerage charges for the order
	Brokerage float32                         `json:"brokerage,omitempty"`
	Taxes     *ProfitAndLossChargesTaxes      `json:"taxes,omitempty"`
	Charges   *ProfitAndLossOtherChargesTaxes `json:"charges,omitempty"`
}
