/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for trades
type TradeData struct {
	// Exchange to which the order is associated
	Exchange string `json:"exchange,omitempty"`
	// Shows if the order was either Intraday, Delivery, CO or OCO
	Product string `json:"product,omitempty"`
	// Shows the trading symbol which could be a combination of symbol name, instrument, expiry date etc
	Tradingsymbol string `json:"tradingsymbol,omitempty"`
	// Shows the trading symbol which could be a combination of symbol name, instrument, expiry date etc
	TradingSymbol string `json:"trading_symbol,omitempty"`
	// Identifier issued by Upstox used for subscribing to live market quotes
	InstrumentToken string `json:"instrument_token,omitempty"`
	// Type of order. It can be one of the following MARKET refers to market order<br>LIMIT refers to Limit Order<br>SL refers to Stop Loss Limit<br>SL-M refers to Stop loss market
	OrderType string `json:"order_type,omitempty"`
	// Indicates whether the order was a buy or sell order
	TransactionType string `json:"transaction_type,omitempty"`
	// The total quantity traded from this particular order
	Quantity int32 `json:"quantity,omitempty"`
	// Unique order ID assigned by the exchange for the order placed
	ExchangeOrderId string `json:"exchange_order_id,omitempty"`
	// Unique order ID assigned internally for the order placed
	OrderId string `json:"order_id,omitempty"`
	// User readable time at when the trade occurred
	ExchangeTimestamp string `json:"exchange_timestamp,omitempty"`
	// Price at which the traded quantity is traded
	AveragePrice float32 `json:"average_price,omitempty"`
	// Trade ID generated from exchange towards traded transaction
	TradeId string `json:"trade_id,omitempty"`
	// The order reference ID for which the order must be modified
	OrderRefId string `json:"order_ref_id,omitempty"`
	// User readable timestamp at which the order was placed
	OrderTimestamp string `json:"order_timestamp,omitempty"`
}
