/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

type OAuthClientExceptionCauseSuppressed struct {
	StackTrace       []OAuthClientExceptionCauseStackTrace `json:"stackTrace,omitempty"`
	Message          string                                `json:"message,omitempty"`
	LocalizedMessage string                                `json:"localizedMessage,omitempty"`
}
