/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for position details
type PositionData struct {
	// Exchange to which the order is associated
	Exchange string `json:"exchange,omitempty"`
	// The quantity/lot size multiplier used for calculating P&Ls
	Multiplier float32 `json:"multiplier,omitempty"`
	// Net value of the position
	Value float32 `json:"value,omitempty"`
	// Profit and loss - net returns on the position
	Pnl float32 `json:"pnl,omitempty"`
	// Shows if the order was either Intraday, Delivery, CO or OCO
	Product string `json:"product,omitempty"`
	// Key issued by Upstox for the instrument
	InstrumentToken string `json:"instrument_token,omitempty"`
	// Average price at which the net position quantity was acquired
	AveragePrice float32 `json:"average_price,omitempty"`
	// Net value of the bought quantities
	BuyValue float32 `json:"buy_value,omitempty"`
	// Quantity held previously and carried forward over night
	OvernightQuantity int32 `json:"overnight_quantity,omitempty"`
	// Amount at which the quantity is bought during the day
	DayBuyValue float32 `json:"day_buy_value,omitempty"`
	// Average price at which the day qty was bought. Default is empty string
	DayBuyPrice float32 `json:"day_buy_price,omitempty"`
	// Amount at which the quantity was bought in the previous session
	OvernightBuyAmount float32 `json:"overnight_buy_amount,omitempty"`
	// Quantity bought in the previous session
	OvernightBuyQuantity int32 `json:"overnight_buy_quantity,omitempty"`
	// Quantity bought during the day
	DayBuyQuantity int32 `json:"day_buy_quantity,omitempty"`
	// Amount at which the quantity is sold during the day
	DaySellValue float32 `json:"day_sell_value,omitempty"`
	// Average price at which the day quantity was sold
	DaySellPrice float32 `json:"day_sell_price,omitempty"`
	// Amount at which the quantity was sold in the previous session
	OvernightSellAmount float32 `json:"overnight_sell_amount,omitempty"`
	// Quantity sold short in the previous session
	OvernightSellQuantity int32 `json:"overnight_sell_quantity,omitempty"`
	// Quantity sold during the day
	DaySellQuantity int32 `json:"day_sell_quantity,omitempty"`
	// Quantity left after nullifying Day and CF buy quantity towards Day and CF sell quantity
	Quantity int32 `json:"quantity,omitempty"`
	// Last traded market price of the instrument
	LastPrice float32 `json:"last_price,omitempty"`
	// Day PnL generated against open positions
	Unrealised float32 `json:"unrealised,omitempty"`
	// Day PnL generated against closed positions
	Realised float32 `json:"realised,omitempty"`
	// Net value of the sold quantities
	SellValue float32 `json:"sell_value,omitempty"`
	// Shows the trading symbol of the instrument
	Tradingsymbol string `json:"tradingsymbol,omitempty"`
	// Shows the trading symbol of the instrument
	TradingSymbol string `json:"trading_symbol,omitempty"`
	// Closing price of the instrument from the last trading day
	ClosePrice float32 `json:"close_price,omitempty"`
	// Average price at which quantities were bought
	BuyPrice float32 `json:"buy_price,omitempty"`
	// Average price at which quantities were sold
	SellPrice float32 `json:"sell_price,omitempty"`
}
