/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for cancel or exit order request
type CancelOrExitMultiOrderData struct {
	// Reference order IDs
	OrderIds []string `json:"order_ids,omitempty"`
}
