/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

type Problem struct {
	// Unique code for the error state
	ErrorCode string `json:"errorCode,omitempty"`
	// Verbose message for the error state
	Message string `json:"message,omitempty"`
	// Path to property failing validation
	PropertyPath string `json:"propertyPath,omitempty"`
	// Invalid value for the property failing validation
	PInvalidValue *interface{} `json:"invalidValue,omitempty"`

	InvalidValue *interface{} `json:"invalid_value,omitempty"`
}
