/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for Balance
type UserFundMarginData struct {
	// Positive values denote the amount blocked into an Open order or position.  Negative value denotes the amount being released.
	UsedMargin float32 `json:"used_margin,omitempty"`
	// Instant payin will reflect here
	PayinAmount float32 `json:"payin_amount,omitempty"`
	// Amount blocked on futures and options towards SPAN
	SpanMargin float32 `json:"span_margin,omitempty"`
	// Payin amount credited through a manual process
	AdhocMargin float32 `json:"adhoc_margin,omitempty"`
	// The amount maintained for withdrawal
	NotionalCash float32 `json:"notional_cash,omitempty"`
	// Total margin available for trading
	AvailableMargin float32 `json:"available_margin,omitempty"`
	// Amount blocked on futures and options towards Exposure
	ExposureMargin float32 `json:"exposure_margin,omitempty"`
}
