/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for trade wise data details
type TradeWiseProfitAndLossData struct {
	// The quantity of stock traded
	Quantity float32 `json:"quantity,omitempty"`
	// ISIN of the stock
	Isin string `json:"isin,omitempty"`
	// Name of the scrip traded
	ScripName string `json:"scrip_name,omitempty"`
	// FUT - Futures   OPT - Options    EQ - Equity
	TradeType string `json:"trade_type,omitempty"`
	// The date on which the stock was bought
	BuyDate string `json:"buy_date,omitempty"`
	// The average rate at which each quantity of the stock was bought
	BuyAverage float32 `json:"buy_average,omitempty"`
	// The date on which the stock was sold
	SellDate string `json:"sell_date,omitempty"`
	// The average rate at which each quantity of the stock was sold
	SellAverage float32 `json:"sell_average,omitempty"`
	// Total buy amount
	BuyAmount float32 `json:"buy_amount,omitempty"`
	// Total sell amount
	SellAmount float32 `json:"sell_amount,omitempty"`
}
