/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Get OHLC values for all instruments across various timeframes
type IntraDayCandleData struct {
	Candles [][]interface{} `json:"candles,omitempty"`
}
