/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

type MarketQuoteSymbol struct {
	Ohlc  *Ohlc     `json:"ohlc,omitempty"`
	Depth *DepthMap `json:"depth,omitempty"`
	// Time in milliseconds at which the feeds was updated
	Timestamp string `json:"timestamp,omitempty"`
	// Key issued by Upstox for the instrument
	InstrumentToken string `json:"instrument_token,omitempty"`
	// Shows the trading symbol of the instrument
	Symbol string `json:"symbol,omitempty"`
	// The last traded price of symbol
	LastPrice float64 `json:"last_price,omitempty"`
	// The volume traded today on symbol
	Volume int64 `json:"volume,omitempty"`
	// Average price
	AveragePrice float64 `json:"average_price,omitempty"`
	// Total number of outstanding contracts held by market participants exchange-wide (only F&O)
	Oi float64 `json:"oi,omitempty"`
	// The absolute change from yesterday's close to last traded price
	NetChange float64 `json:"net_change,omitempty"`
	// The total number of bid quantity available for trading
	TotalBuyQuantity float64 `json:"total_buy_quantity,omitempty"`
	// The total number of ask quantity available for trading
	TotalSellQuantity float64 `json:"total_sell_quantity,omitempty"`
	// The lower circuit of symbol
	LowerCircuitLimit float64 `json:"lower_circuit_limit,omitempty"`
	// The upper circuit of symbol
	UpperCircuitLimit float64 `json:"upper_circuit_limit,omitempty"`
	// Time in milliseconds at which last trade happened
	LastTradeTime string  `json:"last_trade_time,omitempty"`
	OiDayHigh     float64 `json:"oi_day_high,omitempty"`
	OiDayLow      float64 `json:"oi_day_low,omitempty"`
}
