/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Execution summary for multi order request
type MultiOrderSummary struct {
	// The total number of order lines present in the payload.
	Total int32 `json:"total,omitempty"`
	// The number of order lines that were successfully placed without any errors.
	Success int32 `json:"success,omitempty"`
	// The number of order lines that encountered errors during processing, despite their payloads being valid.
	Error_ int32 `json:"error,omitempty"`
	// The number of order lines with payload errors, indicating formatting or data validity issues.<br/><br/><b>Note</b>: Orders are processed only if the entire batch is free of payload_error, ensuring error-free transactions.
	PayloadError int32 `json:"payload_error,omitempty"`
}
