/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for order details
type OrderData struct {
	// Exchange to which the order is associated
	Exchange string `json:"exchange,omitempty"`
	// Price at which the order was placed
	Price float32 `json:"price,omitempty"`
	// Shows if the order was either Intraday, Delivery, CoverOrder or OneCancelsOther
	Product string `json:"product,omitempty"`
	// Quantity with which the order was placed
	Quantity int32 `json:"quantity,omitempty"`
	// Indicates the current status of the order. Valid order status’ are outlined in the table below
	Status string `json:"status,omitempty"`
	// Tag to uniquely identify an order
	Tag string `json:"tag,omitempty"`
	// Order validity (DAY- Day and IOC- Immediate or Cancel (IOC) order)
	Validity string `json:"validity,omitempty"`
	// Average price at which the qty got traded
	AveragePrice float32 `json:"average_price,omitempty"`
	// The quantity that should be disclosed in the market depth
	DisclosedQuantity int32 `json:"disclosed_quantity,omitempty"`
	// Unique order ID assigned by the exchange for the order placed
	ExchangeOrderId string `json:"exchange_order_id,omitempty"`
	// User readable time at which the order was placed or updated
	ExchangeTimestamp string `json:"exchange_timestamp,omitempty"`
	// Identifier issued by Upstox used for subscribing to live market quotes
	InstrumentToken string `json:"instrument_token,omitempty"`
	// Signifies if the order is an After Market Order
	IsAmo bool `json:"is_amo,omitempty"`
	// Indicates the reason when any order is rejected, not modified or cancelled
	StatusMessage string `json:"status_message,omitempty"`
	// Unique order ID assigned internally for the order placed
	OrderId string `json:"order_id,omitempty"`
	// Apart from 1st order it shows the count of how many requests were sent
	OrderRequestId string `json:"order_request_id,omitempty"`
	// Type of order. It can be one of the following MARKET refers to market order<br>LIMIT refers to Limit Order<br>SL refers to Stop Loss Limit<br>SL-M refers to Stop loss market
	OrderType string `json:"order_type,omitempty"`
	// In case the order is part of the second or third leg of a CO or OCO, the parent order ID is indicated here
	ParentOrderId string `json:"parent_order_id,omitempty"`
	// Shows the trading symbol of the instrument
	Tradingsymbol string `json:"tradingsymbol,omitempty"`
	// Shows the trading symbol of the instrument
	TradingSymbol string `json:"trading_symbol,omitempty"`
	// User readable timestamp at which the order was placed
	OrderTimestamp string `json:"order_timestamp,omitempty"`
	// The total quantity traded from this particular order
	FilledQuantity int32 `json:"filled_quantity,omitempty"`
	// Indicates whether the order was a buy or sell order
	TransactionType string `json:"transaction_type,omitempty"`
	// If the order was a stop loss order then the trigger price set is mentioned here
	TriggerPrice float32 `json:"trigger_price,omitempty"`
	// Uniquely identifies the user
	PlacedBy string `json:"placed_by,omitempty"`
	// Order complexity
	Variety string `json:"variety,omitempty"`
}
