/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// Response data for market live status
type MarketStatusData struct {
	Exchange    string `json:"exchange,omitempty"`
	Status      string `json:"status,omitempty"`
	LastUpdated int64  `json:"last_updated,omitempty"`
}
