/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/upstock_sdk-api/upstock_sdk-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/upstock_sdk-api/upstock_sdk-codegen.git)
 */
package upstock_sdk

// instruments
type Instrument struct {
	// Instrument Key of the Instrument
	InstrumentKey string `json:"instrument_key"`
	// Quantity of the instrument to buy or sell for margin calculation
	Quantity int32 `json:"quantity"`
	// Product with which the order is to be placed
	Product string `json:"product"`
	// Indicates whether its a BUY or SELL order
	TransactionType string `json:"transaction_type"`
	// price
	Price float64 `json:"price,omitempty"`
}
